name: "Webhook Event example"

on:
  repository_dispatch:
    types:
      - webhook

jobs:
  webhook_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print event
        run: echo "Event of type: $GITHUB_EVENT_NAME"
